import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";
import { allVaultsSchema, type AllVaults } from "./all-vaults.js";
import { cardTypeSchema, type CardType } from "./card-type.js";
import { paymentTypeSchema, type PaymentType } from "./payment-type.js";
import { expirationMonth2Schema, type ExpirationMonth2 } from "./unions/expiration-month2.js";
import { expirationYear2Schema, type ExpirationYear2 } from "./unions/expiration-year2.js";

/** alias to credit_card_attributes */
export type PaymentProfileAttributes = {
  /**
   * (Optional) Token received after sending billing information using Maxio.js (formerly
   * Chargify.js). This token must be passed as a sole attribute of `payment_profile_attributes`
   * (e.g., tok_9g6hw85pnpt6knmskpwp4ttt).
   */
  chargifyToken?: string;
  id?: number;
  paymentType?: PaymentType;
  /**
   * (Optional) First name on card or bank account. If omitted, the first_name from customer
   * attributes will be used.
   */
  firstName?: string;
  /**
   * (Optional) Last name on card or bank account. If omitted, the last_name from customer
   * attributes will be used.
   */
  lastName?: string;
  maskedCardNumber?: string;
  /** The full credit card number (string representation, e.g., 5424000000000015) */
  fullNumber?: string;
  /**
   * (Optional, used only for Subscription Import) If you know the card type (e.g., Visa, MC, etc.)
   * you may supply it here so that we may display the card type in the UI.
   */
  cardType?: CardType;
  /**
   * (Optional when performing a Subscription Import via vault_token, required otherwise) The 1- or
   * 2-digit credit card expiration month, as an integer or string, e.g., 5
   */
  expirationMonth?: ExpirationMonth2;
  /**
   * (Optional when performing a Subscription Import via vault_token, required otherwise) The
   * 4-digit credit card expiration year, as an integer or string, e.g., 2012
   */
  expirationYear?: ExpirationYear2;
  /**
   * (Optional, may be required by your product configuration or gateway settings) The credit card
   * or bank account billing street address (e.g., 123 Main St.). This value is merely passed
   * through to the payment gateway.
   */
  billingAddress?: string;
  /** (Optional) Second line of the customer’s billing address, e.g., Apt. 100 */
  billingAddress2?: string | null;
  /**
   * (Optional, may be required by your product configuration or gateway settings) The credit card
   * or bank account billing address city (e.g., “Boston”). This value is merely passed through to
   * the payment gateway.
   */
  billingCity?: string;
  /**
   * (Optional, may be required by your product configuration or gateway settings) The credit card
   * or bank account billing address state (e.g., MA). This value is merely passed through to the
   * payment gateway. This must conform to the
   * [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes) in order to be valid for
   * tax locale purposes.
   */
  billingState?: string;
  /**
   * (Optional, may be required by your product configuration or gateway settings) The credit card
   * or bank account billing address country, required in [ISO_3166-1
   * alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format (e.g., “US”). This value is
   * merely passed through to the payment gateway. Some gateways require country codes in a specific
   * format. Check your gateway’s documentation. If creating an ACH subscription, only US is
   * supported at this time.
   */
  billingCountry?: string;
  /**
   * (Optional, may be required by your product configuration or gateway settings) The credit card
   * or bank account billing address zip code (e.g., 12345). This value is merely passed through to
   * the payment gateway.
   */
  billingZip?: string;
  /**
   * (Optional, used only for Subscription Import) The vault that stores the payment profile with
   * the provided vault_token.
   */
  currentVault?: AllVaults;
  /**
   * (Optional, used only for Subscription Import) The “token” provided by your vault storage for an
   * already stored payment profile
   */
  vaultToken?: string;
  /**
   * (Optional, used only for Subscription Import) (only for Authorize.Net CIM storage or Square)
   * The customerProfileId for the owner of the customerPaymentProfileId provided as the vault_token
   */
  customerVaultToken?: string;
  customerId?: number;
  paypalEmail?: string;
  /**
   * (Required for Square unless importing with vault_token and customer_vault_token) The nonce
   * generated by the Square Javascript library (SqPaymentForm)
   */
  paymentMethodNonce?: string;
  /**
   * (Optional) This attribute is only available if MultiGateway feature is enabled for your Site.
   * This feature is in the Private Beta currently. gateway_handle is used to directly select a
   * gateway where a payment profile will be stored in. Every connected gateway must have a unique
   * gateway handle specified. Read [Multigateway
   * description](https://chargify.zendesk.com/hc/en-us/articles/4407761759643#connecting-with-multiple-gateways)
   * to learn more about new concepts that MultiGateway introduces and the default behavior when
   * this attribute is not passed.
   */
  gatewayHandle?: string;
  /**
   * (Optional, may be required by your gateway settings) The 3- or 4-digit Card Verification Value.
   * This value is merely passed through to the payment gateway.
   */
  cvv?: string;
  /**
   * (Optional, used only for Subscription Import) If you have the last 4 digits of the credit card
   * number, you may supply them here so that we may create a masked card number (e.g.,
   * XXXX-XXXX-XXXX-1234) for display in the UI. Last 4 digits are required for refunds in Auth.Net.
   */
  lastFour?: string;
};

export const paymentProfileAttributesSchema: Schema<PaymentProfileAttributes> =
  s.object<PaymentProfileAttributes>({
    chargifyToken: s.optional(s.string()),
    id: s.optional(s.int()),
    paymentType: s.optional(s.lazy(() => paymentTypeSchema)),
    firstName: s.optional(s.string()),
    lastName: s.optional(s.string()),
    maskedCardNumber: s.optional(s.string()),
    fullNumber: s.optional(s.string()),
    cardType: s.optional(s.lazy(() => cardTypeSchema)),
    expirationMonth: s.optional(s.lazy(() => expirationMonth2Schema)),
    expirationYear: s.optional(s.lazy(() => expirationYear2Schema)),
    billingAddress: s.optional(s.string()),
    billingAddress2: s.optionalNullable(s.string()),
    billingCity: s.optional(s.string()),
    billingState: s.optional(s.string()),
    billingCountry: s.optional(s.string()),
    billingZip: s.optional(s.string()),
    currentVault: s.optional(s.lazy(() => allVaultsSchema)),
    vaultToken: s.optional(s.string()),
    customerVaultToken: s.optional(s.string()),
    customerId: s.optional(s.int()),
    paypalEmail: s.optional(s.string()),
    paymentMethodNonce: s.optional(s.string()),
    gatewayHandle: s.optional(s.string()),
    cvv: s.optional(s.string()),
    lastFour: s.optional(s.string()),
    _keysMap: {
      chargifyToken: "chargify_token",
      paymentType: "payment_type",
      firstName: "first_name",
      lastName: "last_name",
      maskedCardNumber: "masked_card_number",
      fullNumber: "full_number",
      cardType: "card_type",
      expirationMonth: "expiration_month",
      expirationYear: "expiration_year",
      billingAddress: "billing_address",
      billingAddress2: "billing_address_2",
      billingCity: "billing_city",
      billingState: "billing_state",
      billingCountry: "billing_country",
      billingZip: "billing_zip",
      currentVault: "current_vault",
      vaultToken: "vault_token",
      customerVaultToken: "customer_vault_token",
      customerId: "customer_id",
      paypalEmail: "paypal_email",
      paymentMethodNonce: "payment_method_nonce",
      gatewayHandle: "gateway_handle",
      lastFour: "last_four",
    },
  });
